### PR TITLE
 Modify ButtonComponent

### PR DESCRIPTION
**Pull request by leo-he-1**
… and added onPress prop

### CODE REVIEW

**Comment by Dulaya** [comment]
* Move containerStyle (Button.tsx) to the end of array in `style={[]}` of TouchableOpacity.
   * This will allow the custom style to override the default styles.
   * Should look like this:

          style={[
             styles.container, 
             buttonClickableStyle,
             {
                backgroundColor: buttonTheme, 
                borderWidth: currentButtonOutline,
                borderColor: buttonOutlineColor,
             },
             containerStyle, 
          ]}

* Add `padding: size.sm` to container in Button.styles.ts
* Okay to remove buttonOutline Button.type.ts and Button.tsx
   * I don't know if Lasha told you to create buttonOutline, but it's unnecessary in my opinion. 
   * This is because user can pass example `containerStyle={{borderWidth: 1, borderColor: "green"}}` to create border.

**Comment by rahmiunalan** [comment]
no conflict merge ok

**Review by rahmiunalan — APPROVED** [review]
looks ok

**Review by aahenry51 — APPROVED** [review]

**Review by Dulaya — APPROVED** [review]
Looks like you made the changes according to the recommendation.

**Pull request merged**
