### PR TITLE
ListItem

### PR DESCRIPTION
**Pull request by leo-he-1**

### CODE REVIEW

**Comment by Dulaya** [comment]
- Change borderRadius to be about 16
- Change title fontSize to be about 18
   - Add fontWeight: 'bold' to Title style
- Change subTitle fontSize to be a little smaller than title's
- Change price fontSize to be about 16
- Change itemQuantity fontSize to be about 16
   - Add fontWeight: 'bold'
- Add marginHorizontal of about 16 to ItemQuantity.
- Remove paddingHorizontal from:
   - Title
   - SubTitle
   - Price
- Add paddingHorizontal: 27 to TextContainer
- Remove paddingHorizontal from Contain.
   - This is because whoever will build Cart screen will set the padding for the screen to align the component evenly.
- To simplify your code, just hard code the Minus icon for leftIcon, Plus for rightIcon and Cross for toRightIconName.
Remove them from props and types. This is because the Cross, Plus and Minus will ALWAYS be there for your component. 
- You can combine iconWidth and iconHeight into one variable: iconSize since they're the same. 
- Lastly, the most imprtant change is to chande the TouchableOpacity around the entire component to View and 
wrap each of the three icons (Cross, Minus and Plus) with their own TouchableOpacity like this:

        <TouchableOpacity onPress={pressCross}>
          <View style={styles.TopRightIconContainer}>
            <Icon name={'Cross'} width={25} height={25}/>
          </View>
        </TouchableOpacity>

Make sure you pass down the onPress function correctly. You may need to change the type file too.  

Your component should look some like this:

image

**Comment by leo-he-1** [comment]
image

**Review by Dulaya — APPROVED** [review]

**Comment by aahenry51** [comment]
Are you going to push the app.tsx? I don't mind, the app.tsx is just another example.

**Review by aahenry51 — APPROVED** [review]

**Review by lasharela — APPROVED** [review]

**Review by Nap1400 — APPROVED** [review]

**Comment by raynesmike** [comment]
fix the conflict first before you merge

**Review by raynesmike — APPROVED** [review]
I approve this

**Pull request merged**
