### PR TITLE
PhoneRegistration Screen

### PR DESCRIPTION
**Pull request by carizzuti**

### CODE REVIEW

**Comment by carizzuti** [comment]
Screenshot_1651188394

**Review by Nap1400 — APPROVED** [review]

**Review by mshago — APPROVED** [review]
Looks great, but you're missing the background color

**Comment by Dulaya** [comment]
- Beware of this **Warning: Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.**
   - Basically it says that your importing stuff from navigation, use it in phoneregistration, reimport stuff from phoneregistration and use it in navigation. It’s allowed, but metro is throwing warning. 
   - I don’t know exactly how to solve it, but for short-term fix I did: 
      - import {EAuthNavigationRoutes} from '../../navigation/authNavigation/AuthNavigation.type';
      - instead of import { EAuthNavigationRoutes } from '../../navigation'; like you did
- Don’t forget to use Miguel’s Container after it’s merged. Currently under review. 
   - Remove padding from your container.
- Don’t forget to change background color to color.white like Miguel said.
- Alphi is working on the background image:
image
- Add shadow like the one from your tag like this inside your button and textinput container: 
   - shadowColor: 'black',
   - elevation: size.lg,
image
image

**Review by Dulaya — APPROVED** [review]

**Review by lasharela — APPROVED** [review]

**Review by raynesmike — APPROVED** [review]
I approve this addition

**Comment by raynesmike** [comment]
Make sure you pull and resolve conflict before merging

**Pull request merged**
